# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (C) 2018-2021 Marek Vasut <marex@denx.de>
#

obj-$(CONFIG_ARCH_SOCFPGA_AGILEX) += clk-agilex.o
obj-$(CONFIG_ARCH_SOCFPGA_AGILEX7M) += clk-agilex.o
obj-$(CONFIG_ARCH_SOCFPGA_ARRIA10) += clk-arria10.o
obj-$(CONFIG_ARCH_SOCFPGA_N5X) += clk-n5x.o
obj-$(CONFIG_ARCH_SOCFPGA_N5X) += clk-mem-n5x.o
obj-$(CONFIG_ARCH_SOCFPGA_AGILEX5) += clk-agilex5.o
obj-$(CONFIG_ARCH_SOCFPGA_AGILEX72) += clk-agilex72.o
obj-$(CONFIG_ARCH_SOCFPGA_AGILEX72) += agilex72-clkmgr.o
obj-$(CONFIG_ARCH_SOCFPGA_AGILEX72) += agilex72-handoff-parser.o
obj-$(CONFIG_ARCH_SOCFPGA_AGILEX72) += agilex72-handoff-source.o
obj-$(CONFIG_AGILEX72_CLKMGR_HANDOFF_EMBED_DEMO) += agilex72-handoff-blob-demo.o
